subscription_id = "71a493c0-e420-4676-ab7c-c5d0ea5128a4"

workloads = {
  "rg01" = {
    name_prefix          = "uat-rg01"
    rg_name              = "uat-rg01"
    location_primary     = "eastus"
    location_secondary   = "southindia"
    linux_vm_name        = "uat-linux-01"
    windows_vm_name      = "uat-win-01"
    datafactory_name     = "uat-df-01"
    keyvault_name        = "uat-kv-01"
    log_analytics_name   = "uat-law-01"
    sql_server_name      = "uat-sql-01"
    sql_location         = "eastasia"
    sql_admin_login      = "uatsqladmin01"
    storage_account_name = "uatstg01"
    app_service_name     = "uat-web-01"
    app_service_location = "westus3"
  }

  "rg02" = {
    name_prefix          = "uat-rg02"
    rg_name              = "uat-rg02"
    location_primary     = "eastus"
    location_secondary   = "southindia"
    linux_vm_name        = "uat-linux-02"
    windows_vm_name      = "uat-win-02"
    datafactory_name     = "uat-df-02"
    keyvault_name        = "uat-kv-02"
    log_analytics_name   = "uat-law-02"
    sql_server_name      = "uat-sql-02"
    sql_location         = "eastasia"
    sql_admin_login      = "uatsqladmin02"
    storage_account_name = "uatstg02"
    app_service_name     = "uat-web-02"
    app_service_location = "westus3"
  }

  "rg03" = {
    name_prefix          = "uat-rg03"
    rg_name              = "uat-rg03"
    location_primary     = "eastus"
    location_secondary   = "southindia"
    linux_vm_name        = "uat-linux-03"
    windows_vm_name      = "uat-win-03"
    datafactory_name     = "uat-df-03"
    keyvault_name        = "uat-kv-03"
    log_analytics_name   = "uat-law-03"
    sql_server_name      = "uat-sql-03"
    sql_location         = "eastasia"
    sql_admin_login      = "uatsqladmin03"
    storage_account_name = "uatstg03"
    app_service_name     = "uat-web-03"
    app_service_location = "westus3"
  }

  "rg04" = {
    name_prefix          = "uat-rg04"
    rg_name              = "uat-rg04"
    location_primary     = "eastus"
    location_secondary   = "southindia"
    linux_vm_name        = "uat-linux-04"
    windows_vm_name      = "uat-win-04"
    datafactory_name     = "uat-df-04"
    keyvault_name        = "uat-kv-04"
    log_analytics_name   = "uat-law-04"
    sql_server_name      = "uat-sql-04"
    sql_location         = "eastasia"
    sql_admin_login      = "uatsqladmin04"
    storage_account_name = "uatstg04"
    app_service_name     = "uat-web-04"
    app_service_location = "westus3"
  }
}
